root = "/app"
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "migrations"]
  include_ext = ["go"]
  kill_delay = "0s"
  rerun_delay = 500

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
